name: ideanet_wacv_2022
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.15.1
  - scikit-image=0.14.2
  - scipy=1.1.0
  - pillow=4.1.0
  - pip=19.0.2
  - yaml=0.1.7
  - pip:
    - opencv-python==3.4.2.17
    - keras==1.9.0
    - tensorflow-gpu==1.5.0
