name: ideanet_wacv_2022
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scikit-image
  - scipy
  - pillow
  - pip
  - yaml
  - pip:
    - opencv-python
    - keras
    - tensorflow-gpu
